steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/oxypald-grafana/oxypals-grafana-artrepo/grafana', '.' ]
images:
- 'us-central1-docker.pkg.dev/oxypald-grafana/oxypals-grafana-artrepo/grafana'
options:
  logging: 'CLOUD_LOGGING_ONLY'  # Or 'NONE'
